Fix ci

diff --git a/.github/workflows/wall_guidance-ci.yaml b/.github/workflows/wall_guidance-ci.yaml
--- a/.github/workflows/wall_guidance-ci.yaml
+++ b/.github/workflows/wall_guidance-ci.yaml
@@ -11,13 +11,12 @@ jobs:
       - name: make_compile_commands.json
         run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
       
-      - name: clang-tidy-review
-        - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-        # Optionally generate compile_commands.json
+      # Optionally generate compile_commands.json
 
-        - uses: ZedThree/clang-tidy-review@v0.6.0
-        id: review
-        # If there are any comments, fail the check
-        - if: steps.review.outputs.total_comments > 0
-          run: exit 1
+      - uses: ZedThree/clang-tidy-review@v0.6.0
+      id: review
+      # If there are any comments, fail the check
+      - if: steps.review.outputs.total_comments > 0
+        run: exit 1
