Fix ci

diff --git a/.github/workflows/wall_guidance-ci.yaml b/.github/workflows/wall_guidance-ci.yaml
--- a/.github/workflows/wall_guidance-ci.yaml
+++ b/.github/workflows/wall_guidance-ci.yaml
@@ -1,49 +1,23 @@
-name: ros1-melodic-ci
+name: clang-tidy-review
 
-on:
-  pull_request:
-    paths-ignore:
-      - '**.md'
+# You can be more specific, but it currently only works on pull requests
+on: [pull_request]
+
 jobs:
-  clang-tidy:
-    runs-on: ubuntu-18.04
+  build:
+    runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v2
-    - name: Install clang-tidy
-      run: |
-        git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_server.git
-        cd  ros_setup_scripts_Ubuntu18.04_server
-        bash step0.bash
-        bash step1.bash
-        cd ..
-    - name: Install clang-tidy
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y clang-tidy
-    - name: Prepare compile_commands.json
-      run: |
-        source /opt/ros/melodic/setup.bash
-        cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-    - name: Create results directory
-      run: |
-        mkdir clang-tidy-result
-    - name: Analyze
-      run: |
-        ls -a
-        git diff -U0 HEAD^ | clang-tidy-diff -p1 -path build -export-fixes clang-tidy-result/fixes.yml
-    - name: Run clang-tidy-pr-comments action
-      # Don't run this Action if fixes.yml doesn't exist - clang-tidy may not generate it in some cases
-      if: ${{ hashFiles( 'clang-tidy-result/fixes.yml' ) != '' }}
-      uses: platisd/clang-tidy-pr-comments@master
-      with:
-        # The GitHub token (or a personal access token)
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        # The path to the clang-tidy fixes generated previously
-        clang_tidy_fixes: clang-tidy-result/fixes.yml
-        # Optionally set to true if you want the Action to request
-        # changes in case warnings are found
-        request_changes: true
-        # Optionally set the number of comments per review
-        # to avoid GitHub API timeouts for heavily loaded
-        # pull requests
-        suggestions_per_comment: 10
+      - name: make_compile_commands.json
+        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+      
+      - name: clang-tidy-review
+        - uses: actions/checkout@v2
+
+        # Optionally generate compile_commands.json
+
+        - uses: ZedThree/clang-tidy-review@v0.6.0
+        id: review
+        # If there are any comments, fail the check
+        - if: steps.review.outputs.total_comments > 0
+          run: exit 1
